#+title:      Twelve score and ten years ago, our fathers ...
#+subtitle: Family stories from the 18th century
#+date:       [2026-04-10 Fri 07:37]
#+Author: George Morrison Jones
#+email: gmj@pobox.com
#+filetags:   :18th:biography:public:revolution:
#+identifier: 20260224T073758
#+signature:  1776=our=faimly
#+last_saved: 2026-04-11 12:43
#+BIBLIOGRAPHY: family.bib
#+cite_export: csl chicago-fullnote-bibliography.csl
#+OPTIONS: author:t date:t 
#+OPTIONS: html-postamble:nil
#+LATEX_COMPILER: pdflatex
#+LATEX_HEADER: \usepackage{pmboxdraw}
#+LATEX_HEADER: \usepackage{titling}
#+LATEX_HEADER: \preauthor{\begin{center}\large}
#+LATEX_HEADER: \postauthor{\par\normalsize gmj@pobox.com\end{center}}
#+OPTIONS: email:nil
#+latex_class: article
#+latex_class_options: [titlepage]
#+MACRO: conditional-title (eval (if (org-export-derived-backend-p org-export-current-backend 'latex) "#+OPTIONS: title:t" "#+OPTIONS: title:nil"))
{{{conditional-title}}}

* Twelve score and ten years ago, our fathers ...
#+begin_quote
“Twelve Score and Ten Years ago our fathers brought forth on this continent a new nation, conceived in liberty, and dedicated to the proposition that all men are created equal.  Now we are engaged in a great civil war, testing whether that nation, or any nation so conceived and so dedicated, can long endure...

-- Abraham Lincoln, mostly.
#+end_quote

** Intro
On the 150th anniversary of the battle of Gettysburg, our Boy Scout troop camped on the battlefield.
Our scoutmaster, Harvey Leister, made sure to take us by the Leister house which was Union general Meade's headquarters.  The decision to fight on was made in that house and the course of the Civil War changed.
A blizzard canceled our scheduled trip to camp at Valley Forge. Bad weather at Valley Forge?
Everybody came to our house instead, made snow shelters and /tried/ to sleep outside.

Stories are important to who we are. What was the last thing you did that you are proud of? Stories are important to families. Why were you born where you were? Stories are important to nations. Where in the past could your nation have avoided a big mistake? Can we (I) learn from that now? Shared stories are what brings us together.

As the United States approaches its 250th birthday, this is my attempt to tell some of the stories of our family as they intersect with the story of the the United States. I will focus mostly on 18th century. I'm working back the family line of my mothers parents, George Leonard Morrison (1885-1974) and Esther Free Morrison (1910-2003). This is not genealogy, though we are fortunate to know a lot of that [cite:@BowdleGenealogy2024][cite:@CragoGenealogy1981][cite:@JonesGenealogy1970] . This is an outgrowth of a personal project to capture oral history (exactly why did my grandfather bite his sister when she was his school teacher...? Who was killed by a dead horse as it was being removed from a barn? Where did my great-great grandfather hide runaway slaves on their escape to Canada?...). 

Some things are worth remembering and celebrating. "We hold these truths to be self evident...". Some things are mistakes to learn form and move on. "I can not tell a lie". As we move forward we should remember the stories that got us here. Stories bind us together and stories drive us apart.   Grandma (Esther Free Morrison) was a great lover of poetry.   I can still hear her voice reciting this poem:

#+begin_verse
“He drew a circle that shut me out-
Heretic, rebel, a thing to flout.
But love and I had the wit to win:
We drew a circle and took him In!”

― Edwin Markham

#+end_verse

The American story is inclusive.

** Timeline

Just to put things in context, here's a timeline:

  - 1754-1763 :: French and Indian War.  Washington fires first shot?
  - 1763 :: King George indirectly grants George Washington Land in the west.
  - 1763 :: British forbid settlement west of the mountains.
  - 1776-1781 :: American Revolution.  Oh yea?  Stop me...
  - 1788 :: Ohio Company founds Marietta in the new NW Territory
  - 1795 :: Treaty of Greenville.  Indians basically out of Ohio.
  - 1795-1820 :: Flood-gates of settlers opens.  Many revolutionary war veterans getting "free" land for their service, or simply for occupying it.
  - 1803 :: Ohio becomes the 17th state.

** Our Stories
*** Welcome to the Buckeye State
*Amos Porter, Sr 1742-1807*

- The year is 1775.  You're in Massachusetts, just outside Boston. You're just minding your own business when this guy comes galloping through town in the middle of the night yelling "The British[fn:6] are coming, the British are coming" and he didn't mean the Beatles. You grab your gun and go[fn:4]  One hundred or so years later our distant "Cousin Henry" Longfellow (we both go back to John Alden and Priscilla Mullins on the  Mayflower in 1620) will write a poem about that night that starts:

  #+begin_verse
  Listen, my children, and you shall hear
  Of the midnight ride of Paul Revere,
  On the eighteenth of April, in Seventy-Five:
  Hardly a man is now alive
  Who remembers that famous day and year. ...
  
  ...
  One if by land, and two if by sea;
  And I on the opposite shore will be,
  ...
  #+end_verse



  Last year I visited Lexington and Concord with sons Bryan and Daniel Jones.


  
  *Amos Porter, Jr 1769-1861*
  
- The year is 1788. Your father was one of the militiamen called up the night of Paul Revere's ride. A group calling itself "The Ohio Company" recruits you and other young men from New England with the goal of establishing the first settlement in the newly created Northwest territory. At Pittsburgh you and 47 others[cite:@CutlerFounders1888] board boats to journey down the Ohio. Of course one of the boats is named "The Mayflower", because, again, you are all from New England. At the mouth of the Muskingum river, your party lands and founds a new city. The city is named Marietta after the current queen of France, Marie Antoinett. She has not yet lost her head in the soon-to-unfold French Revolution. France came to your aid in the recently concluded American Revolution. Washington won't even be president until the following year, but your party decides to name the first county in Ohio for him now ! [fn:3]

- For a couple years you help Marietta get off the ground. The Ohio country looks pretty good. Then you /walk/ back to Massachusetts. 3 years later, in 1795, you
  bring your whole family back, start a farm and settle down.  It helps that the treaty of Greenville was signed that year.  As you move west, the natives are, like it or not, moving further west.
  Of course you call the town/township you found just north of Marietta "Salem", because, again, you're from Massachusetts.

- Amos Porter Sr., your father who was call to arms April 19, 1775, farms just across the stream near the new village of Lower Salem in Washington County.[fn:5] At 14 miles north of the Ohio River, your family will soon be involved in the "Underground Railroad", helping runaway slaves make it to freedom and fighting for the Union in the Civil war. But those are stories of the 19th century. This is mostly about events in the 18th century.
  
- Simon Porter, your brother, also lives near you and has a daughter named Lois Porter.  She will marry into the Gould family, another New England family that settled in the area. Family names stick, her great granddaughter (my mother) will be named Lois Morrison (Jones).
 
- You would probably not understand the phrase "Go Bucks" or know how to answer the call "O-H-", but your father's descendants sure do.   Your decisions worked out pretty well for his posterity. Thanks.

*** Road Trip

Back to me. Twenty some years ago (2003) our family moved from Ohio to Northern Virginia.
Since then we've been doing regular road trips to both Pittsburgh and Ohio to see
family. In the process, we've inadvertently re-discovered George Washington's favorite
route to Cumberland, MD, where his ill-fated adventures at Ft. Necessity and with
Braddock began.

Washington's favorite route is our favorite route.  We head west from Winchester VA, usually stop at Shawnee Springs (French and Indian war, anyone?), continue through the little town of Bloomery, WV ("On The Road to Everywhere") and turn right across a one lane bridge on Gaston Road to take a 1/2 mile shortcut on the way to Paw Paw and Cumberland.  As it turns out....

 On April 23, 1750 a young George Washington surveyed this very land, 388 acres including the cut-through at the "Forks of the Capon" for one Henry Enochs, Sr.[cite:CutlerFounders1888]  who was my 4-Great grandfather. The next day (per one source) Enochs assisted Washington on a neighbor's survey.  The next year, on April 24, 1751 he surveyed a tract for my 3-Great grandfather Enoch Enochs.[cite:@WashingtonSurvey1751]
 And, yes, one of his descendants married "Morris Morrison", who needs a first and a last name when one will do? 
 
I researched and feed more primary source materials including Washington's diary, survey records and military orders to "The AIs" (Anthropic's "Claude" in this case) and got the following summary.  It's AI, so caveat machinator:

#+begin_quote
The documentary record now supports a continuous, multi-decade relationship
between Washington and Henry Enochs rooted in the specific geography of the
Forks of the Cacapon:

| Year      | Event                                          | Source                        | Confidence  |
|-----------+------------------------------------------------+-------------------------------+-------------|
| 1750      | GW surveys Enochs's tract on Cacapon River     | Papers of GW, 02-01-02-0004   | *Confirmed* |
| 1753      | Enochs receives 388-acre patent on survey      | NNk Deeds & Grants, Book H    | *Confirmed* |
| 1753      | GW passes through Capon corridor (diplo. msn.) | GW Journal 1754               | Route only  |
| 1754      | GW passes through corridor (Ft. Necessity)     | Papers of GW, Vol. 1          | Route only  |
| 1755      | Enochs builds fort at Forks after Braddock     | Papers of GW diary note       | *Confirmed* |
| 1755      | Enochs appears in GW orders/correspondence     | Founders Archives (r=3, r=4)  | *Confirmed* |
| 1756      | GW recommends Enochs's fort in defense plan    | DLC:GW (LC Washington Papers) | *Confirmed* |
| 1761      | Enochs receives further 271½-acre grant        | NNk Deeds & Grants, Book K    | *Confirmed* |
| Oct. 1770 | GW records "Fort at Henry Enochs" as waypoint  | GW Diary 8 Oct 1770           | *Confirmed* |
| Nov. 1770 | GW dines at Enochs at Fork of Cacapehon        | GW Diary 28 Nov 1770          | *Confirmed* |

The relationship arc is: *client/surveyor* (1750) → *frontier neighbor on a
strategic road* (1753–1755) → *component of Washington's military defense
network* (1755–1758) → *established waypoint and personal acquaintance*
(1770). This is substantially more documented than most Washington frontier
connections outside of major military figures.
#+end_quote

After Washington's surrender at Ft. Necessity, the settlements in Hampshire county became the front line.
If not held, the area provided the French and Indians a "back door" into the hart of Virginia.  Washington
urged the construction a line of forts with "Fort Enochs" or "Enoch's Fort" on one end, and several others
including Fort Edwards[fn:7].

And this is all before the revolution.  Per genealogy records[cite:@BowdleGenealogy2024] from cousin John Bowdle, several members of the Enochs family (Captian Henry Enochs, Enoch Enochs)  volunteered during the revolution. Of course a family that had sustained personal contact with George Washington would join his army.

The Enoch's (Henry) also appear to have been moving into Green and Washington counties in the southwest corner of Pennsylvania (1774). Washington County PA was named for George Washington even before the battle of Yorktown. They would later move to Nobel County Ohio where they would become part of the Morrison family line.[fn:2]

As you cross the stream on Gaston Road on the one lane bridge, there is an old cemetery on the hill next to the road and an old farm house.   I keep meaning to stop there and see "who" I can find.  I never have. Mom (Lois Morrison Jones, d. 2013) did stop a few times and reported that even the letters on the stones are
faded away.  And the stream keeps flowing.

*** Born Frei
It seems you only get interested in your family history after you hit 60 or so, when those who could have told you more about it are gone. I often heard Great Anut Bess Butler nee Free (d. 2005 at 102) say she wished she'd listened more when she was young. She said she remembered being shown where "The Hessian" was buried, "somewhere over by Bainbridge", but she forgot it . 

My grandmother's name was Esther Free.  We were always told that the family came from "a Hessian" who fought in the revolution, had "jumped ship", changed his name and somehow wound up in Ohio.  I thought that's all that was known about it, but I guess I just wasn't listening.

I'm trying to resist diving deep down the genealogy research rabbit hole as I write these stories, but it turns out I have a fairly detailed genealogy of the Free family courtesy of my grandmothers best childhood friend Laura Crago nee Free.  More on the Cragos later.

I found this in the Free genealogy:

#+begin_quote
"NOBEL CRAWFORD made his house near the present location of Lyndon station ... MR CRAWFORD sold to FREDERICK FREE in 1800, and removed to Paint Township [which is near Bainbridge, so Aunt Bess was right] where he afterward made his home.

MR FREE came to this country during the war of the Revolution, as a hessian soldier in the service of King George.  He soon after deserted the service of the English king and espoused the cause of the patriots, in whose ranks he fought during the war.  He married in the east and lived to receive a pension for his services".[fn:1]
#+end_quote


And then I came across an 8 page handwritten[fn:9] manuscript[cite:@MorrisonManuscript1980c] by my grandmother, the first several pages of which were copies of historical records of "The Hessian", the remainder of which were her memories of who-married-who through the 19th and mid 20th centuries and memories of early visits with the now quite large Free clan.   It turns out she did both know and care about her heritage.  I just wasn't listening.


Here is the first quote from her manuscript:

#+begin_quote
Frederick Free was the ancestor of the family in both Highland and Ross Counties. He was a Hessian soldier brought to America by England to fight the Colonists. However, when taken prisoner, he let it be known that he was a Patriot in favor of the American Cause.

He emigrated to the area of Lyndon, Ohio, Ross County in 1800. He had a large family..." [the tradition continued, Grandma, b. 1910 was one of 11 Free kids...]

From "Highland Pioneers Sketches & Family Genealogies" Page 454 [cite:@AyresGenealogy1971]
#+end_quote

and the second, from a Lawyer's family is, of course, verbose:

#+begin_quote
The writer's ancestral family of Free is of German origin and has been traced back to the time of the Revolutionary War. The earliest ancestor Frederick Free (no. 1475 in book) was among the thousands of Hessian mercenary soldiers brought by the British Government to fight with the Redcoats against the American Colonists during the Colonists' struggle for independence. Frederick deserted the British army, espoused the American Cause, married and settled in Ross County, Ohio where he became a respected citizen. His surname in his native Hesse Cassel is not known. It could have been the German equivalent of Free, which he could have anglicized when he came to America. There is also the possibility that he adopted the name as an alias when he deserted the Hessian ranks, or to exemplify his freedom to the New Country.

Col. John W. Free, who was a practitioner of law, but is now living in New Lexington, comes of a family  honorable and distinguished. He was born in Stewartstown, York Co., Pa., Aug. 8th, 1830. His paternal grandfather was a native of Hesse Cassel, Germany and he and two brothers came from the Fatherland to the New World to fight in the English army at the time of the Revolutionary War. They were present when Lord Cornwallis' army surrendered to General Washington at York Town. Having formed an attachment for the New World the grandfather of the subject determined to remain and located in Baltimore, Maryland, while one of the brothers took up abode in North Carolina.

The first names of the three Hessians were not mentioned by the biographer. Dr. John Free was the father of Col. John W. Free. Dr. John was a minister also, married Catherine Newman of Chambersburg, Pa., moved to Mansfield and practiced medicine. Dr. John Free was the father of Immortal J. N. Free[fn:8].

Vale, Walker, Littler  [cite:@ValeGenealogy1973]
#+end_quote

We have Frederick Free's will from Ross County, "prooved", so, died 1837?  The genealogy records indicate he was born in Hesse-Cassel, Germany 1755.  He and most of his 9 children appear to have come from Berkeley County VA (now WV), near where I live now, to Ross county Ohio.

The Recent (2025) Ken Burns/PBS documentary "The American Revolution" made a point of mentioning that a lot of the Hessian soldiers stayed on in America and some even went home and brought their families back from
Germany.  So "our" experience seems not to have been uncommon.  I highly recommend the documentary.

His story could be re-phrased as "Illegal immigrant comes to America. Skips out on his employer. Marries a local. Has lots of kids. Runs off to somewhere in the Midwest. Works hard. Makes good." That sounds like an American story to me.

And, finally, I came across this
#+begin_quote
"In Bainbridge [Township] lived Friederich FREI, who came to the Scioto Valley in 1811."[cite:@SmithGermanSettlers2009]
#+end_quote

We have our man who was "Born Frei", but died "Free". 

*** The Crago Connection

It's been said that everyone in the world can be connected via 7 links. The joke in our family is "Stephanie [my wife] is in every one of those links". She's one degree away from George Bush and the Kennedy clan, having answered the phone at work once when Arnold Swartzenegger called about setting up a community event. She's one degree away from Gerald Ford having met his son Mike though his work at college ministry. We've been in Mennonite circles for 30+ years where EVERYBODY is connected. Stephanie knows ALL the Miller-Yoder-Swartz-Bender-Byler-Swartzentruber family interconnections.

She was adopted and we don't know her family history, so she doesn't get to play
in this family story. Right? Wrong.  Stephanie has connections.   Stephanie always has connections.

One of the first settlers of Green County, PA family was one Thomas Crago, who was killed by Indians (1771). That story is recounted below.

But wait, there's more. Stephanie's adoptive grandmother was a Crago. The family had, so the story goes, land grants in western PA form William Penn. They also retained family stories about the killing of Thomas Crago.

But wait, there's still more. The genealogy[cite:@CragoGenealogy1981] we have of my grandmother Free's family was compiled by her best childhood friend, Laura Free Crago (a cousin?). We've not traced it down but we think that a branch of
the Crago family made it's way from western PA to Ross County Ohio where (at least) one married into the Free family.

But wait, there still still more.  Capitan Enoch Henry of later Revolutionary War fame and his brother Enoch Enochs, our ancestor for whom George Washington had surveyed land were also in Green County, PA around the same time (1774) before some of them moved on to Ohio where they became part of our family line.  They lived in "Enoch's Garrison", so, maybe taking cues from their experience in French and Indian War and the recent (1771) murder of Thomas Crago they had decided to live in a "Garrison".  It was a rough world out there, because...

*** People had different stories in mind

Some people had different stories in mind.   The Indian's own stories didn't include loosing their land.
Things often don't go well when people adopt different stories:

The Find-A-Grave site has this [[https://www.findagrave.com/memorial/30898977/thomas-crago][version of the story of the killing of Thomas Crago]]. This jib more-or-less with the oral traditon in Stephanie's  family:

#+begin_quote
Thomas Crago was killed about 1771 (often reported as 1770), when he resisted an attempt by several Indians to take his horse without permission, after traveling to a neighbor's home to borrow a butter churn. The place where he died is today in Greene Co., PA. At the time of his death, it was claimed by both Pennsylvania and Virginia, and Greene Co. had not yet been organized. Virginia referred to this area as Yohogania County, Virginia. It is reported that he was living with two young sons in a lean-to at the time of his death.
#+end_quote


I grew up in Franklin County (they liked Old Ben back then), just south of the Delaware county line. Why was there a Delaware county Ohio? Because the Lanape (Delaware) who had been the natives round Philadelphia when William Penn showed up (1682?) kept getting driven west. By the time Ohio was "settled" 1780s-early 1800s they were living in Ohio. I recommend /This Very Ground, This Crooked Affair: A Mennonite Homestead on Lenape Land/ by John Ruth that tells a triple tale of loss of the very same land (by the Lanape, William Penn and his own family). 

According to the AIs (Claude Code) there are 81 cities in the US today with populations over 1000 that have "Fort" in their name: Fort Worth TX, Fort Wayne IN, Fort Lauderdale FL, Fort Collins CO, Fort Smith AR, Fort Myers FL, Fort Pierce FL, Fort Dodge AI.  There are 100s of smaller towns or former fort locations.  I don't think they were all there because the neighbors were rolling out the red carpet and and welcoming the new arrivals.

During the revolution, in 1782, American forces in Ohio massacred 96 Indians at Gnadenhutten.  The Indians had all been converted to a pacifist strain of Christianity by the Moravian missionaries.  They went to their deaths praying and singing Christian hymns.

The Indians returned the favor in 1791 at a place called Big Bottom 30 miles north of Marietta where Amos Porter had landed in 3 years prior (1788) and about 15 miles from where the Porter and Gould families (see below would settle).

All was not sweetness and light.  Everybody was not on the same page.  Everyone did not have the same story.

*** You say you want a revolution?


What I've been trying to do in this write-up is chronicle our family's connection to major events in American history in the 18th century. I've done so largely by drawing connections based on the barest details of peoples lives: when and where they were born, when and where died, who were their children, etc.  In a few cases we have stories about them or their involvement in certain battles, etc.   But in no case do I have first-hand, personal knowledge of the people involved.  I'm just painting pictures from the scraps I have.

What follows is Ephriam Gould's obituary of his father Benjamin Gould. This is the heart felt tribute of a son to one of the founding generation. Benjamin Gould just missed the revolution, being 16 at the close of the war, but he lost a brother at the battle of Monmouth, and his father and brother were part of the force under Horatio Gates and Benedict Arnold that captured British general Bergoyne and his entire army at Saratoga, convincing the French to enter the war and setting the stage for Yorktown.

Ephriam Gould, who was himself a dominant figure in our family in the 19th century[fn:11], tells us about that generation, about his father's values, and how the events of the revolution impacted him for the rest of his life. He tells the story as no other could:


 #+begin_example
Filename: 1849_DEC_21_Benjamin_Gould_Obit_by_Ephraim_Gould (Transcription_JEB_CDB).doc
Letter from Morrison archives
Transcribed 26-FEB-2014 by John E. Bowdle
Corrections 27-FEB-2014 by Charles Bird
Corrections 06-MAR-2026 by George Morrison Jones
All third great grandsons of Benjamin Gould
Spelling and lack of punctuation maintained
- - - - -
 #+end_example  

 #+begin_quote
 Dide in Salem Township Washington Co Ohio on the 21st of December 1849  Benjamin Gould was born in Brookfield Tp Massachusetts  he removed from that place to Marietta in this place Co 1808  in 1810 he removed to this Township where he resided till his death  The welfare of the church and of the country were two prominent traits in his character  he would dwell on those topics with peculiar interest and solicitude  The events of those revolutionary struggles which separated us from the Mother Country remained forever in his memory till the close of his life he being 16 years old at the close of the war  his Father and Brother were among that noble band that captured the proud and formidable army of Bergoyne and his brother was engaged in a number of the most severe battles of the revolution  the _____ and protracted and Death like  struggle at the battle of Monmouth brought on a disease that occasioned his brothers premature death  Thus having a correct nowledge of the sacrifice and treasuns and blood that our countrys freedom cost  he watched the political changes of the country with a patriots anxiety and care  he would dwell on the great course of universal liberty with feeling of deep interest and he gave evidence that the countrys welfare occupied his mind by going several miles to deposit his vote in the ballot box after he was 4 score years old  He was a member of the P church  he was an invaluable supporter of reveiled religion thoe and the friends of piety feel they have lost a substantiat advovocate of the cause and the oldest of his children cannot remember the time when morning and evening devotions was not atended to with conscious punctuality in his house

 
 [Page 2]
 
___  ______ the closing scene of his earthly existence drew near that confidence in the savior which he had enjoyed through life continued to comfort him and shed the light of a happy immortality on the gloom of the grave he endured his affliction which was severe and lingering without a murmuring word and wielded up his spirit willingly in to the hands of his creator

The relatives of father Gould feele they have lost a faithful moni?ter?and a wise and judicious councellor

The writer of this memoir looks back to on his last associations with the deceased with mingled emotions of passing through the labor and toiles of the day he has passed a  pleasant hour conversing with and listening to remarks of him and his children experience untold pleasures in the reflections that his life and death both witness that the waves of Gordian  only placed him in a situation when God with his soft hand will wipe all tears from his eyes

									E G
							[Presumed to be Ephraim Gould]
 #+end_quote

** Where are we?
I think I need to sit with this for a while and reflect.

I was able to document far more involvement in the revolution than I expected: Lexington and Concord, Saratoga, Monmouth, a Hessian fighting for the British switching sides and joining Washington at Yorktown. 

 Our family story in America began in 1620 with "nonconformists" who wanted to be English but worship differently than the church of England. It continued through the revolution (and later the Civil war) where "our fathers" thought it worth fighting for Jefferson's proposition that "All men are created equal". Those ideas have spanned the globe in the last 250 years, from the botched French Revolution to most anti-colonialist revolutions of the 19th and 20th centries, to the emancipation proclamation, to Ephriam Gould's daughter Cahtarine (Kate) Gould Morrison getting the right to vote in 1920[fn:10], to the civil rights movement of my youth.  It is these ideas that have made the American story.  It is, in part, these  ideas that have made us as a family who we are.

* References
#+print_bibliography:
 
* Footnotes
[fn:11] See [cite:@gould1959covered] for glimpses of "Grandfather Gould" and life in the Lower Salem community in the late 19th Century.  The author, Charlie Gould, did much of the geological work that found the major oil deposits in Texas and the American southwest.
[fn:10] I'm not sure if this will make it into other planned biographical sketches, but this one is worth recording here.   When Grandma (Esther Free Morrison) married into the Morrison family in 1929, 9 years after women got the vote, Grandpa apparently had the county Republican party chair come over to talk to her about voting the "right way".  The Morrisons were Republicans.   Grandma several times told me proudly "My people were Democrats."  I don't know how she marked the ballots, but she had a fiercely independent streak her whole life.
[fn:9] Grandma's handwriting was perfect.  The "AIs" only get about %60-%80 of my handwriting correct when asked to OCR (read, transcribe) it.  I don't think they made a single mistake with her impeccable pennmanship". 
[fn:8]
The "Immortal J.N. Free" deserves a write-up all his own. He was a character and more than a family legend from the mid 19th to early 20th century. . Google him: [[https://www.google.com/search?q=the+immortal+jn+free][https://www.google.com/search?q=the+immortal+jn+free]]
He was most likely off his rocker, but a spell-binding speaker who talked is way into free passes on all the railroads of the time
and was known to be able to pass the Union and Confederate lines without question.   I have correspondence form Esther Free Morrison to people in Northern Ohio had older, probably 2nd hand stories about him.  Aunt Bess (b. 1902) had some stories of him.  I may document what I know of him (Grandma's letters, the scraps of oral history). Here is just one of the many stories floating around about him:
https://www.thestarpress.com/story/news/local/2018/05/27/bygone-muncie-immortal-j-n-free-paid-many-visits-delaware-county/629123002/#:~:text=J.N.%20is%20not%20only%20an,there%2C%20his%20story%20becomes%20legend. 
[fn:1] Quote found in copy of typewritten page  in [cite:@CragoGenealogy1981] which in turns cites [cite:@WilliamsBrosRossHighland1880]

[fn:7] See https://fortedwards.org/history-2/  for info about Fort Edwards and the string of forts that Washington urged Virgina to build.

[fn:6] Actually in April of 1775, Paul Revere would probably have said something like "The Regulars" are coming.
At this point everybody thought of themselves as British.  That would start to change around 5 AM that morning when the "Shot heard round the world" was fired on Lexington Green.   The American story was begun.
[fn:5] The British Library thinks that the History of Washington County, Ohio (around Marietta) is important enough to include in it's series of reprints of significantly important source documents of the American (post) colonial period. See [cite:@WilliamsWashingtonCo1881]. The sections on Salem Township and the biographical sketches of the Porter family contain a lot of material about (and collected from) our family. I've been to Lower Salem/Duck Creek/"Mt. Ephriam" church 3 or 4 times. I know where the farms of the Morrisons and the Goulds were. I've heard stories about several the people mentioned in the history and have heirlooms from a few of them.  Would recommend reading if it you want more insights (e.g. why was our family rabid Methodists when we came from Congregationalist New England stock?) 

[fn:4] The following entry is found in  [cite:@JonesGenealogy1970]
#+begin_verse
  Porter, Amos.  Chelsea, Mass.  Private.  Capt. Sprague's Co. of
  Militia which marched to the alarm of April 19, 1775;  discharged
  May 16, 1775; service 1 month.

  The above information is recorded in the office of the Secretary,
  Archives Division
  Commonwealth of Massachusetts
  Office of the Secretary
  State House, Boston, 33, Mass.
  #+end_verse
[fn:2] The migration to Green County, PA is documented in depth in [cite:@KeithEnochs1923]  which was copied in in [cite:@JonesGenealogy1970]
[fn:3] Much of this story is recounted in  [cite:@McCulloughPioneers2019] 

* Appendix - Genealogy

I didn't want to go here.  I didn't want to turn this into a genealogy, but I realize there are too many names flying around to keep straight. With that said, I'm going to include a brief genealogy chart of the
direct ancestors of my grandparents George Leonard Morrison and Esther Free Morrison.  I will only include people in our direct family line or who are mentioned.  If you want to go down the Genealogy rabbit hole,
see the genealogies and materials in the references section and/or contact me directly.  John Bowdle has been
doing sustained genealogy for 40 or 50 years and still lives in the area his family moved to in 1800.  Here is a condensed genealogy:  

#+begin_example
Amos Porter Sr. (1742-1807) — Called up, 1775, Lexington & Concord
├── Amos Porter Jr. (1769-1861) — founder, Marietta, Lower Salem
└── Simon Porter (1779-1843)
    └── Lois Porter (1808-1859)
        m. Ephraim Gould (1805-1882), son of Benjamin Gould (1767-1849)
        └── Catharine (Kate) L. Gould (1846-1939)
           m. Elisha F. Morrison (1840-1906) — Union Army, Civil War
           └── George Leonard Morrison (1885-1974)
              m. Esther Free Morrison (1910-2003) — desc. of Frederick Free, "The Hessian"
              └── Lois Morrison Jones (1936-2013) 
#+end_example



